### ISSUE TITLE
Add cleanup code

### ISSUE THREAD

**Issue by Boris-Dimov** [FRUE-Project/fpkg#10]
**Describe le bug**
Currently our code has no cleanup functionality, which is *bad.* We should def look into this.

**Comment by Kaper365** [comment]
WDYM with cleanup functionality? Like, deletion of tmp files after execution?

**Comment by Boris-Dimov** [comment]
Exactly. Afaik for now it should only purge /tmp/fpkg-cache/, right

**Comment by Kaper365** [comment]
I think that would be right, I'm on it rn

**Comment by Kaper365** [comment]
Done in bd7d9f5b4e835ed6a1967ad9205cd7e85310ba54
